# coding:utf-8
from selenium import webdriver
from selenium.webdriver.support.select import Select
from time import sleep
profile_directory = r'C:\Users\Administrator\AppData\Roaming\Mozilla\Firefox\Profiles\e6bsauke.default'
profile = webdriver.FirefoxProfile(profile_directory)
driver=webdriver.Firefox(profile)
driver.get("http://192.168.40.236:8089/console/common/index.htm")
driver.maximize_window()
driver.find_element_by_xpath(".//*[@id='txUserId']").send_keys("admin")
driver.find_element_by_xpath(".//*[@id='passwordId']").send_keys("123456")
driver.find_element_by_xpath("html/body/div[1]/div[2]/form/div[3]/input").click()
sleep(2)
driver.find_element_by_xpath("html/body/div[3]/ul/li[3]/a").click()
sleep(2)
driver.find_element_by_xpath("html/body/div[4]/div/div[2]/div/div[2]/div/ul/li[1]/a").click()
sleep(2)
driver.find_element_by_xpath(".//*[@id='form_loan']/div/div[1]/div[2]/div[1]/div[2]/a[1]").click()
sleep(3)
driver.find_element_by_xpath(".//*[@id='contractCode']").send_keys("88888")
driver.find_element_by_xpath(".//*[@id='userAccountLi']/input").send_keys("13046176334")
s1 = driver.find_element_by_xpath(".//*[@id='assetType']")
Select(s1).select_by_value("3")
driver.find_element_by_xpath(".//*[@id='uploader']").send_keys(u"小姐姐")
driver.find_element_by_xpath(".//*[@id='loanTitle']").send_keys(u"debx-13个月0918_3")
s2 = driver.find_element_by_xpath(".//*[@id='tab1']/ul/li[7]/div[3]/select[1]")
Select(s2).select_by_value("440000")
s3 = driver.find_element_by_xpath(".//*[@id='tab1']/ul/li[7]/div[3]/select[2]")
Select(s3).select_by_value("440100")
s4 = driver.find_element_by_xpath(".//*[@id='xianSlt']")
Select(s4).select_by_value("440103")
driver.find_element_by_xpath(".//*[@id='address']").send_keys(u"489号")
driver.find_element_by_xpath(".//*[@id='jkje']").send_keys("300")
s5 = driver.find_element_by_xpath(".//*[@id='guaranteeMeasureSelect']")
Select(s5).select_by_value("3")
driver.find_element_by_xpath(".//*[@id='authTypeLi']/div[2]/input[1]").click()
driver.find_element_by_xpath(".//*[@id='authTypeLi']/div[2]/input[2]").click()
driver.find_element_by_xpath(".//*[@id='authTypeLi']/div[2]/input[3]").click()
s6 = driver.find_element_by_xpath(".//*[@id='jkytSelect']")
Select(s6).select_by_value(u"资金周转")
driver.find_element_by_xpath(".//*[@id='jkqx']").clear()
driver.find_element_by_xpath(".//*[@id='jkqx']").send_keys("13")
driver.find_element_by_xpath(".//*[@id='annualRate']").send_keys("8")
driver.find_element_by_xpath(".//*[@id='borrowerInterestRate']").send_keys("9")
s10 = driver.find_element_by_xpath(".//*[@id='hkfs']")
# Select(s10).select_by_value(u"MYFX")
Select(s10).select_by_value(u"DEBX")
# Select(s10).select_by_value(u"YCFQ")
s7 = driver.find_element_by_xpath(".//*[@id='hklySelect']")
Select(s7).select_by_value(u"工资收入")
driver.find_element_by_xpath(".//*[@id='nextStepButton']").click()
sleep(3)
driver.find_element_by_xpath(".//*[@id='saveBtn']/input[3]").click()
sleep(3)
s8 = driver.find_element_by_xpath(".//*[@id='entrustPayeeSelect']")
Select(s8).select_by_value("0")
driver.find_element_by_xpath(".//*[@id='form1']/div[1]/div[1]/ul/li[18]/div[2]/input").send_keys(u"技术")
driver.find_element_by_xpath(".//*[@id='form1']/div[1]/div[1]/ul/li[19]/div[2]/input").send_keys(u"489号")
s9 = driver.find_element_by_xpath(".//*[@id='subjectNatureSelect']")
Select(s9).select_by_value("1")
driver.find_element_by_xpath(".//*[@id='loanTitle']").send_keys(u"小姐姐")
driver.find_element_by_xpath(".//*[@id='SB']/input[1]").click()
driver.find_element_by_xpath(".//*[@id='SB']/input[2]").click()
driver.find_element_by_xpath(".//*[@id='SB']/input[3]").click()
driver.find_element_by_xpath(".//*[@id='test']").click()
sleep(3)
driver.find_element_by_xpath("html/body/div[5]/div/div[1]/div/div/div[2]/div[2]/div[2]/a[1]").click()

# 审核
sleep(1)
driver.find_element_by_xpath(".//*[@id='form_loan']/div/div[2]/table/tbody/tr[3]/td[15]/a[1]").click()
sleep(1)
driver.find_element_by_xpath("html/body/div[4]/div/div[1]/div/div[1]/div[2]/div[1]/div/ul/li[4]/a").click()
sleep(1)
driver.find_element_by_xpath("html/body/div[5]/div/div[1]/div/div/div[2]/div[2]/div[2]/a[1]").click()